-- 2026 NBA Draft — Round 2 prospects (bank distractors, picks 31-60)
-- These appear in the player bank but have no first-round result slots
insert into draft_prospects (year, name, position, school) values
  (2026, 'B. Thornton',    'PG', 'Ohio State'),
  (2026, 'R. Saunders',    'SG', 'BYU'),
  (2026, 'I. Evans',       'SF', 'Duke'),
  (2026, 'M. Thomas',      'SG', 'Arkansas'),
  (2026, 'T. Brazile',     'PF', 'Arkansas'),
  (2026, 'B. Miller',      'SF', 'Cincinnati'),
  (2026, 'R. Conwell',     'SG', 'Louisville'),
  (2026, 'B. Smith',       'PG', 'Purdue'),
  (2026, 'J. Kayil',       'PG', 'Alba Berlin'),
  (2026, 'D. Mitchell',    'SF', 'St. John''s'),
  (2026, 'O. Oweh',        'SG', 'Kentucky'),
  (2026, 'J. Gillespie',   'PG', 'Tennessee'),
  (2026, 'T. Bilodeau',    'PF', 'UCLA'),
  (2026, 'M. Brown',       'PF', 'Duke'),
  (2026, 'E. Sharp',       'SG', 'Houston'),
  (2026, 'F. Okpara',      'C',  'Tennessee'),
  (2026, 'T. Nickel',      'SG', 'Vanderbilt'),
  (2026, 'T. Lawal',       'PF', 'Virginia Tech'),
  (2026, 'B. Hopkins',     'SF', 'St. John''s'),
  (2026, 'J. Bradley',     'PG', 'Arizona'),
  (2026, 'I. Nelson',      'PF', 'South Florida'),
  (2026, 'H. Veesaar',     'C',  'North Carolina'),
  (2026, 'U. Onyenso',     'C',  'Virginia'),
  (2026, 'L. Jones',       'SG', 'Florida State'),
  (2026, 'N. Martinelli',  'SF', 'Northwestern'),
  (2026, 'V. Ishchenko',   'SF', 'PBC Lokomotiv'),
  (2026, 'N. Ngoy',        'C',  'Poitiers B86'),
  (2026, 'J. Pierre Jr.',  'SG', 'SMU'),
  (2026, 'T. Kaufman-Renn','PF', 'Purdue'),
  (2026, 'M. Lewis',       'SF', 'SE Melbourne')
on conflict do nothing;
