-- 2026 NBA Draft prospect schools — run in Supabase SQL editor
UPDATE draft_prospects SET school = 'BYU'               WHERE year = 2026 AND name = 'A. Dybantsa';
UPDATE draft_prospects SET school = 'Kansas'            WHERE year = 2026 AND name = 'D. Peterson';
UPDATE draft_prospects SET school = 'Duke'              WHERE year = 2026 AND name = 'C. Boozer';
UPDATE draft_prospects SET school = 'North Carolina'    WHERE year = 2026 AND name = 'C. Wilson';
UPDATE draft_prospects SET school = 'Illinois'          WHERE year = 2026 AND name = 'K. Wagler';
UPDATE draft_prospects SET school = 'Louisville'        WHERE year = 2026 AND name = 'M. Brown Jr.';
UPDATE draft_prospects SET school = 'Arkansas'          WHERE year = 2026 AND name = 'D. Acuff Jr.';
UPDATE draft_prospects SET school = 'Houston'           WHERE year = 2026 AND name = 'K. Flemings';
UPDATE draft_prospects SET school = 'Michigan'          WHERE year = 2026 AND name = 'M. Johnson Jr.';
UPDATE draft_prospects SET school = 'Arizona'           WHERE year = 2026 AND name = 'B. Burries';
UPDATE draft_prospects SET school = 'Michigan'          WHERE year = 2026 AND name = 'Y. Lendeborg';
UPDATE draft_prospects SET school = 'Michigan'          WHERE year = 2026 AND name = 'A. Mara';
UPDATE draft_prospects SET school = 'Tennessee'         WHERE year = 2026 AND name = 'N. Ament';
UPDATE draft_prospects SET school = 'Washington'        WHERE year = 2026 AND name = 'H. Steinbach';
UPDATE draft_prospects SET school = 'Texas'             WHERE year = 2026 AND name = 'D. Swain';
UPDATE draft_prospects SET school = 'Iowa'              WHERE year = 2026 AND name = 'B. Stirtz';
UPDATE draft_prospects SET school = 'Stanford'          WHERE year = 2026 AND name = 'E. Okorie';
UPDATE draft_prospects SET school = 'Texas Tech'        WHERE year = 2026 AND name = 'C. Anderson Jr.';
UPDATE draft_prospects SET school = 'Santa Clara'       WHERE year = 2026 AND name = 'A. Graves';
UPDATE draft_prospects SET school = 'Kentucky'          WHERE year = 2026 AND name = 'J. Quaintance';
UPDATE draft_prospects SET school = 'New Zealand'       WHERE year = 2026 AND name = 'K. Lopez';
UPDATE draft_prospects SET school = 'Alabama'           WHERE year = 2026 AND name = 'L. Philon Jr.';
UPDATE draft_prospects SET school = 'St. John''s'       WHERE year = 2026 AND name = 'Z. Ejiofor';
UPDATE draft_prospects SET school = 'Baylor'            WHERE year = 2026 AND name = 'C. Carr';
UPDATE draft_prospects SET school = 'Valencia (Spain)'  WHERE year = 2026 AND name = 'S. De Larrea';
UPDATE draft_prospects SET school = 'UConn'             WHERE year = 2026 AND name = 'T. Reed Jr.';
UPDATE draft_prospects SET school = 'Houston'           WHERE year = 2026 AND name = 'C. Cenac Jr.';
UPDATE draft_prospects SET school = 'Iowa State'        WHERE year = 2026 AND name = 'J. Jefferson';
UPDATE draft_prospects SET school = 'UConn'             WHERE year = 2026 AND name = 'A. Karaban';
UPDATE draft_prospects SET school = 'Arizona'           WHERE year = 2026 AND name = 'K. Peat';
