-- Corrected positions for 2026 NBA Draft prospects
UPDATE draft_prospects SET position = 'SF' WHERE year = 2026 AND name = 'A. Dybantsa';
UPDATE draft_prospects SET position = 'SG' WHERE year = 2026 AND name = 'D. Peterson';
UPDATE draft_prospects SET position = 'PF' WHERE year = 2026 AND name = 'C. Boozer';
UPDATE draft_prospects SET position = 'SF' WHERE year = 2026 AND name = 'C. Wilson';
UPDATE draft_prospects SET position = 'SG' WHERE year = 2026 AND name = 'K. Wagler';
UPDATE draft_prospects SET position = 'PG' WHERE year = 2026 AND name = 'M. Brown Jr.';
UPDATE draft_prospects SET position = 'PG' WHERE year = 2026 AND name = 'D. Acuff Jr.';
UPDATE draft_prospects SET position = 'PG' WHERE year = 2026 AND name = 'K. Flemings';
UPDATE draft_prospects SET position = 'PF' WHERE year = 2026 AND name = 'M. Johnson Jr.';
UPDATE draft_prospects SET position = 'SG' WHERE year = 2026 AND name = 'B. Burries';
UPDATE draft_prospects SET position = 'PF' WHERE year = 2026 AND name = 'Y. Lendeborg';
UPDATE draft_prospects SET position = 'C'  WHERE year = 2026 AND name = 'A. Mara';
UPDATE draft_prospects SET position = 'SF' WHERE year = 2026 AND name = 'N. Ament';
UPDATE draft_prospects SET position = 'PF' WHERE year = 2026 AND name = 'H. Steinbach';
UPDATE draft_prospects SET position = 'SG' WHERE year = 2026 AND name = 'D. Swain';
UPDATE draft_prospects SET position = 'PG' WHERE year = 2026 AND name = 'B. Stirtz';
UPDATE draft_prospects SET position = 'PG' WHERE year = 2026 AND name = 'E. Okorie';
UPDATE draft_prospects SET position = 'PG' WHERE year = 2026 AND name = 'C. Anderson Jr.';
UPDATE draft_prospects SET position = 'PF' WHERE year = 2026 AND name = 'A. Graves';
UPDATE draft_prospects SET position = 'PF' WHERE year = 2026 AND name = 'J. Quaintance';
UPDATE draft_prospects SET position = 'SF' WHERE year = 2026 AND name = 'K. Lopez';
UPDATE draft_prospects SET position = 'PG' WHERE year = 2026 AND name = 'L. Philon Jr.';
UPDATE draft_prospects SET position = 'PF' WHERE year = 2026 AND name = 'Z. Ejiofor';
UPDATE draft_prospects SET position = 'SG' WHERE year = 2026 AND name = 'C. Carr';
UPDATE draft_prospects SET position = 'PG' WHERE year = 2026 AND name = 'S. De Larrea';
UPDATE draft_prospects SET position = 'C'  WHERE year = 2026 AND name = 'T. Reed Jr.';
UPDATE draft_prospects SET position = 'PF' WHERE year = 2026 AND name = 'C. Cenac Jr.';
UPDATE draft_prospects SET position = 'PF' WHERE year = 2026 AND name = 'J. Jefferson';
UPDATE draft_prospects SET position = 'SF' WHERE year = 2026 AND name = 'A. Karaban';
UPDATE draft_prospects SET position = 'PF' WHERE year = 2026 AND name = 'K. Peat';
